### ISSUE TITLE
Rendering my table in quarto add the html raw output

### ISSUE THREAD

**Issue by yeroslaviz** [debruine/glossary#6]
I'm playing with the glossary package, which I find a great addition to the quarto world and trying to create a glossary for my web page.

Unfortunately, when rendering  my file, I can see the html code above the table. 
I have treid to avoid that using some filters 
<img width="658" alt="Screenshot 2023-09-28 at 2 55 08 PM" src="https://github.com/debruine/glossary/assets/8927555/5494ddc0-a6b2-4763-ad4a-7eaebcf007f1">

this is how my yml file looks like:

```
...
format: 
  html:
    toc: true
    toc-depth: 4
    toc-expand: true
    number-sections: true
    number-depth: 4
    code-fold: true
    strip-comments: true
    from: 'markdown-markdown_in_html_blocks'
filters:
  - parse-latex
  - code-visibility
 ...
```

But these linse stays there whatever I do.

How can I get rid of them?

thanks

Assa
